local cfg = {}

-- define each group with a set of permissions
-- _config property:
--- gtype (optional): used to have only one group with the same gtype per player (example: a job gtype to only have one job)
--- onspawn (optional): function(player) (called when the player spawn with the group)
--- onjoin (optional): function(player) (called when the player join the group)
--- onleave (optional): function(player) (called when the player leave the group)
--- (you have direct access to vRP and vRPclient, the tunnel to client, in the config callbacks)

cfg.groups = {

	["streamer"] = {
		"-staff.chat"
	},


	["ledelse"] = {
		_config = { gtype = "staff"},
		"blacklisted.weapons",
		"blacklisted.vehicles",
		"player.group.add.staff",
		"player.group.remove.staff",
		"player.givemoney",
		"player.noclip",
		"player.giveitem",
		"player.ban",
		"vehicle.repair",
		"player.kick",
		"player.unban",
		"player.spec",
		"staff.seizable",
		"police.seize.items",
		"police.seize.weapons",
		"player.coords",
		"player.coordsnoheading",
		"admin.besked",
		"admin.revive",
		"player.unlockvehicle",
		"player.repairvehicle",
		"player.deletevehicle",
		"staff.gun",
		"player.spawnvehicle",
		"admin.easy_unjail",
		"admin.spikes",
		"player.tptowaypoint",
		"player.tptome",
		"player.tpto",
		"player.tptocoords",
		"player.freeze",
		"player.whitelist",
		"player.unwhitelist",
		"staff.chat",
		"admin.tickets",
		"player.list",
		"admin.godmode",
		"admin.revive",
	},
	["ban"] = {
		"player.unban",
		"player.ban",
		"staff.chat"
	},

	["refund"] = {
		"player.givemoney",
		"player.giveitem"
	},

	["jobs"] = {
		"player.group.add.staff",
		"player.group.remove.staff"
	},

	["biludvikler"] = {
		"player.deletevehicle",
		"player.spawnvehicle",
		"player.cords",
		"player.kick",
		"player.tptowaypoint",
		"player.tptome",
		"player.tptocoords",
		"player.tpto",
		"player.noclip"
	},

	["supporter"] = {
		_config = { gtype = "staff"},
		"player.whitelist",
		"admin.tickets",
		"player.unwhitelist",
		"player.deletevehicle",
		"admin.besked",
		"admin.revive",
		"player.spec",
		"player.coords",
		"admin.announce",
		"player.kick",
		"player.tptowaypoint",
		"player.list",
		"player.tptome",
		"player.tptocoords",
		"player.unlockvehicle",
		"player.tpto",
		"player.freeze",
		"staff.chat",
		"player.noclip"
	},
	["staff"] = {
		_config = { gtype = "staff"},
		"player.deletevehicle",
		"player.ban",
		"player.group.add.staff",
		"player.group.remove.staff",
		"admin.besked",
		"player.coords",
		"player.spec",
		"admin.tickets",
		"staff.gun",
		"player.unlockvehicle",
		"admin.announce",
		"player.kick",
		"police.menu",
		"staff.seizable",
		"player.repairvehicle",
		"police.seize.weapons",
		"police.seize.items",
		"police.easy_cuff",
		"admin.revive",
		"player.whitelist",
		"player.unwhitelist",
		"player.tptowaypoint",
		"player.list",
		"player.tptome",
		"player.tptocoords",
		"player.tpto",
		"player.freeze",
		"staff.chat",
		"player.noclip",
		"admin.revive",
		"player.spawnvehicle",
	},

	["Højesterets Dommer"] = {
		_config = { gtype = "Dommer-Job",order=2},
		"court.doors",
		"-dommer.paycheck",
		"dommer.wardrobe",
		"dommer.mangroup",
		"dommer.duty",
	},


	["Forsyningen"] = {
		_config = { gtype = "Forsyningen-Job",order=1},
		"lifeinvader.key",
		"forsyningen.loadshop"
	},
	["Forsyningen-Job"] = {
		_config = { gtype = "job"},
		"lifeinvader.key",
		"forsyningen.loadshop"
	},

	["PET"] = {
		"police.menu",
		--"politi.ledelse.doors",
		"police.putinveh",
		"politi.onduty",
		"police.carsearch",
		"player.deletevehicle",
		"police.bodyarmor",
		--"bank.police",
		"police.announce",
		"police.check",
		"player.replaceplate",
		"police.easy_cuff",
		"police.easy_jail",
		"police.easy_unjail",
		"police.getoutveh",
		"police.jail",
		"police.seize.items",
		"police.seize.weapons",
		"police.fine",
		"police.service",
		"police.store_weapons",
		"police.store_money",
		"police.wanted",
		"emergency.revive",
		"police.besked",
		"police.drag",
		"police.easy_fine",
		"police.garage",
		"policeheli.garage",
		"police.loadshop",
		"police.menu_interaction",
		"police.spikes",
		"police.handcuff",
		"police.license",
		"politi.ledelse.doors",
		"police.cloakroom",
		"police.pc",
		"pet.paycheck",
		"tagging.mangroup",
		"producent.adgang",
		"kemiker.adgang",
		"politi.wardrobe",
	},

	["AKS"] = {
		_config = { gtype = "AKS-Job",order=1},
		"police.menu",
		--"politi.ledelse.doors",
		"police.putinveh",
		"politi.onduty",
		"police.pc",
		"aks.vw",
		"politi.duty",
		"aks.duty",
		"police.carsearch",
		"player.deletevehicle",
		"police.bodyarmor",
		"police.announce",
		"police.check",
		"player.replaceplate",
		"police.easy_cuff",
		"police.easy_jail",
		"police.easy_unjail",
		"police.getoutveh",
		"police.jail",
		"police.seize.items",
		"police.seize.weapons",
		"police.fine",
		"police.service",
		"police.store_weapons",
		"police.store_money",
		"police.wanted",
		"emergency.revive",
		"police.besked",
		"police.drag",
		"police.easy_fine",
		"police.garage",
		"aks.garage",
		"policeheli.garage",
		"police.loadshop",
		"police.menu_interaction",
		"police.spikes",
		"police.handcuff",
		"police.license",
		"politi.ledelse.doors",
		"police.cloakroom",
		"police.pc",
		"aks.paycheck",
		"tagging.mangroup",
		"politi.wardrobe",
		"producent.adgang",
		"kemiker.adgang",
		"aks.wardrobe",
	},
		["AKS-Job"] = {
		_config = { gtype = "job"},
		"police.menu",
		--"politi.ledelse.doors",
		"police.putinveh",
		"politi.onduty",
		"police.pc",
		"aks.vw",
		"police.carsearch",
		"player.deletevehicle",
		"police.bodyarmor",
		"bank.police",
		"police.announce",
		"police.check",
		"police.easy_cuff",
		"police.easy_jail",
		"police.easy_unjail",
		"police.getoutveh",
		"police.jail",
		"-police.seizable", -- negative permission, police can't seize itself, even if another group add the permission
		"police.seize.items",
		"police.seize.weapons",
		"police.fine",
		"police.service",
		"police.store_weapons",
		"police.store_money",
		"police.wanted",
		"emergency.revive",
		"police.besked",
		"police.drag",
		"police.easy_fine",
		"police.garage",
		"policeheli.garage",
		"police.loadshop",
		"aks.loadshop",
		"police.menu_interaction",
		"police.spikes",
		"police.handcuff",
		"police.license",
	},


	["Dommer"] = {
		_config = { gtype = "Dommer-Job",order=1},
		"court.doors",
		"dommer.duty",
		"dommer.wardrobe",
		"-dommerchef.paycheck",
	},

	["Dommer-Job"] = {
		_config = { gtype = "job" },
		"dommer.paycheck",
		"dommerchef.paycheck",
		"dommer.garage",
	},
	["Ejendomsmægler Chef"] = {
		_config = { gtype = "Ejendomsmægler-Job",order=2},
		"realestate.key",
		"realestate.duty",
		"-realestate.paycheck",
		"realestate.mangroup",
		"ejendomsmaegler.wardrobe",
	},
	["Ejendomsmægler"] = {
		_config = { gtype = "Ejendomsmægler-Job",order=1},
		"realestate.key",
		"realestate.duty",
		"-realestatechef.paycheck",
		"ejendomsmaegler.wardrobe",
	},
	["Ejendomsmægler-Job"] = {
		_config = { gtype = "job"},
		"realestatechef.paycheck",
		"realestate.paycheck",
		"realestate.key",
		"realestate.onduty",
		"ejendomsmaegler.wardrobe",
	},
	-- ["Psykolog Chef"] = {
	-- 	_config = { gtype = "Psykolog-Job",order=2},
	-- 	"psykolog.key",
	-- 	"psykolog.duty",
	-- 	"-psykolog.paycheck",
	-- 	"psykolog.mangroup",
	-- },
	-- ["Psykolog"] = {
	-- 	_config = { gtype = "Psykolog-Job",order=1},
	-- 	"psykolog.key",
	-- 	"psykolog.duty",
	-- 	"-psykologchef.paycheck"
	-- },
	-- ["Psykolog-Job"] = {
	-- 	_config = { gtype = "job"},
	-- 	"psykologchef.paycheck",
	-- 	"psykolog.paycheck",
	-- },
	["Peds"] = {
		"admin.revive",
	},
	["PedsV2"] = {
	},
	-- ["Journalist Chef"] = {
	-- 	_config = { gtype = "Journalist-Job",order=2},
	-- 	"journalist.duty",
	-- 	"-journalist.paycheck",
	-- 	"journalist.mangroup",
	-- },
	-- ["Journalist"] = {
	-- 	_config = { gtype = "Journalist-Job",order=1},
	-- 	"journalist.duty",
	-- 	"-journalistchef.paycheck",
	-- },
	-- ["Journalist-Job"] = {
	-- 	_config = { gtype = "job"},
	-- 	"weazel.mic",
	-- 	"weazel.camera",
	-- 	"journalist.paycheck",
	-- 	"journalistchef.paycheck",
	-- },
	-- the group user is auto added to all logged players
	["user"] = {
		"player.phone",
		"player.calladmin",
		"user.askid",
		"player.coords",
		"player.coordsnoheading",
		"player.player_menu",
		"carjacker.lockpick",
		"player.fix_haircut",
		"player.store_weapons",
		"player.puton_attachments",
		"player.store_armor",
		"player.phone",
		"player.loot",
		"player.check",
		"player.strip",
		"toggle.service",
		"police.seizable",
		"alle.hvidvask" -- can be seized
	},
	["Bilforhandler Chef"] = {
		_config = { gtype = "Bilforhandler-Job",order=2},
		"bilforhandler.duty",
		"bilforhandler.doors",
		"bilforhandler.mangroup",
		"-bilforhandler.paycheck",
	},
	["Bilforhandler"] = {
		_config = { gtype = "Bilforhandler-Job",order=1},
		"bilforhandler.duty",
		"bilforhandler.doors",
		"-bilforhandlerchef.paycheck",
	},
	["Bilforhandler-Job"] = {
		_config = { gtype = "job"},
		"bilforhandlerchef.paycheck",
		"bilforhandler.paycheck",
		"admin.bilforhandler",
	},
	["Rigspolitichef"] = {
		_config = { gtype = "Politi-Job",order=12},
		"politi.ledelse.doors",
		"police.cloakroom",
		"police.pc",
		"politi.duty",
		"politi.mangroup",
		"-politiviceledelse.paycheck",
		"-policedirector.paycheck",
		"-policeinspector.paycheck",
		"-policevicedirector.paycheck",
		"-policecommissioner.paycheck",
		"-politiassistent.paycheck",
		"-police.paycheck",
		"-pet.paycheck",
		"tagging.mangroup",
		"-politielev.paycheck",
		"producent.adgang",
		"kemiker.adgang",
		"politi.wardrobe",
		"police.licenseGive",
		"politi.assistent.doors",
	},
	["Vice Rigspolitichef"] = {
		_config = { gtype = "Politi-Job",order=11},
		"politi.ledelse.doors",
		"police.cloakroom",
		"police.pc",
		"politi.duty",
		"politi.mangroup",
		"-politiledelse.paycheck",
		"-policedirector.paycheck",
		"-policeinspector.paycheck",
		"-policevicedirector.paycheck",
		"-policecommissioner.paycheck",
		"-politiassistent.paycheck",
		"-police.paycheck",
		"-pet.paycheck",
		"tagging.mangroup",
		"-politielev.paycheck",
		"producent.adgang",
		"kemiker.adgang",
		"politi.wardrobe",
		"police.licenseGive",
		"politi.assistent.doors",
	},
	["Politidirektør"] = {
		_config = { gtype = "Politi-Job",order=10},
		"politi.ledelse.doors",
		"police.cloakroom",
		"police.pc",
		"politi.duty",
		"politi.mangroup",
		"-politiledelse.paycheck",
		"-politiviceledelse.paycheck",
		"-policevicedirector.paycheck",
		"-policeinspector.paycheck",
		"-policecommissioner.paycheck",
		"-politiassistent.paycheck",
		"-police.paycheck",
		"-pet.paycheck",
		"tagging.mangroup",
		"-politielev.paycheck",
		"producent.adgang",
		"kemiker.adgang",
		"politi.wardrobe",
		"police.licenseGive",
		"politi.assistent.doors",
	},
	["Vice Politidirektør"] = {
		_config = { gtype = "Politi-Job",order=9},
		"politi.ledelse.doors",
		"police.cloakroom",
		"police.pc",
		"politi.duty",
		"politi.mangroup",
		"-politiledelse.paycheck",
		"-politiviceledelse.paycheck",
		"-policedirector.paycheck",
		"-policeinspector.paycheck",
		"-policecommissioner.paycheck",
		"-politiassistent.paycheck",
		"-police.paycheck",
		"-pet.paycheck",
		"tagging.mangroup",
		"-politielev.paycheck",
		"producent.adgang",
		"kemiker.adgang",
		"politi.wardrobe",
		"police.licenseGive",
		"politi.assistent.doors",
	},
	["Politiinspektør"] = {
		_config = { gtype = "Politi-Job",order=8},
		"politi.ledelse.doors",
		"police.cloakroom",
		"police.pc",
		"politi.duty",
		"-politiledelse.paycheck",
		"-politiviceledelse.paycheck",
		"-policedirector.paycheck",
		"-policevicedirector.paycheck",
		"-policecommissioner.paycheck",
		"-politiassistent.paycheck",
		"-police.paycheck",
		"-pet.paycheck",
		"tagging.mangroup",
		"-politielev.paycheck",
		"producent.adgang",
		"kemiker.adgang",
		"politi.wardrobe",
		"politi.assistent.doors",
	},
	["Vice Politiinspektør"] = {
		_config = { gtype = "Politi-Job",order=7},
		"politi.ledelse.doors",
		"police.cloakroom",
		"police.pc",
		"politi.duty",
		"-politiledelse.paycheck",
		"-politiviceledelse.paycheck",
		"-policedirector.paycheck",
		"-policevicedirector.paycheck",
		"-policecommissioner.paycheck",
		"-politiassistent.paycheck",
		"-police.paycheck",
		"-pet.paycheck",
		"tagging.mangroup",
		"-politielev.paycheck",
		"producent.adgang",
		"kemiker.adgang",
		"politi.wardrobe",
		"politi.assistent.doors",
	},
	["Politikommisær"] = {
		_config = { gtype = "Politi-Job",order=6},
		"politi.ledelse.doors",
		"police.cloakroom",
		"police.pc",
		"politi.duty",
		"-politiledelse.paycheck",
		"-politiviceledelse.paycheck",
		"-policedirector.paycheck",
		"-policevicedirector.paycheck",
		"-policeinspector.paycheck",
		"-politiassistent.paycheck",
		"-police.paycheck",
		"-pet.paycheck",
		"tagging.mangroup",
		"-politielev.paycheck",
		"producent.adgang",
		"kemiker.adgang",
		"politi.wardrobe",
		"politi.assistent.doors",
	},
	["Politiassistent Første Grad"] = {
		_config = { gtype = "Politi-Job",order=5},
		"police.cloakroom",
		"police.pc",
		"politi.duty",
		"-politiledelse.paycheck",
		"-politiviceledelse.paycheck",
		"-policedirector.paycheck",
		"-policevicedirector.paycheck",
		"-policeinspector.paycheck",
		"-policecommissioner.paycheck",
		"-police.paycheck",
		"-pet.paycheck",
		"tagging.mangroup",
		"-politielev.paycheck",
		"politi.wardrobe",
		"politi.assistent.doors",
	},
	["Politiassistent"] = {
		_config = { gtype = "Politi-Job",order=4},
		"police.cloakroom",
		"police.pc",
		"politi.duty",
		"-politiledelse.paycheck",
		"-politiviceledelse.paycheck",
		"-policedirector.paycheck",
		"-policevicedirector.paycheck",
		"-policeinspector.paycheck",
		"-policecommissioner.paycheck",
		"-police.paycheck",
		"-pet.paycheck",
		"-politielev.paycheck",
		"tagging.mangroup",
		"politi.wardrobe",
		"politi.assistent.doors",
	},
	["Politibetjent"] = {
		_config = { gtype = "Politi-Job",order=3},
		"police.cloakroom",
		"police.pc",
		"politi.duty",
		"-politiledelse.paycheck",
		"-politiviceledelse.paycheck",
		"-policedirector.paycheck",
		"-policevicedirector.paycheck",
		"-policeinspector.paycheck",
		"-policecommissioner.paycheck",
		"-politiassistent.paycheck",
		"-pet.paycheck",
		"-tagging.mangroup",
		"-politielev.paycheck",
		"politi.wardrobe",
	},
	["Politielev"] = {
		_config = { gtype = "Politi-Job",order=2},
		"police.cloakroom",
		"-bank.police",
		"-policeheli.garage",
		"police.pc",
		"politi.duty",
		"-politiledelse.paycheck",
		"-politiviceledelse.paycheck",
		"-policedirector.paycheck",
		"-policevicedirector.paycheck",
		"-policeinspector.paycheck",
		"-policecommissioner.paycheck",
		"-politiassistent.paycheck",
		"-pet.paycheck",
		"-police.paycheck",
		"-tagging.mangroup",
		"politi.wardrobe",
	},
		["Politihund"] = {
    		_config = { gtype = "Politi-Job",order=1},
    		"police.cloakroom",
    		"-bank.police",
    		"-policeheli.garage",
    		"police.pc",
    		"politi.duty",
    		"-politiledelse.paycheck",
    		"-politiviceledelse.paycheck",
    		"-policedirector.paycheck",
    		"-policevicedirector.paycheck",
    		"-policeinspector.paycheck",
    		"-policecommissioner.paycheck",
    		"-politiassistent.paycheck",
    		"-pet.paycheck",
    		"-police.paycheck",
    		"-politielev.paycheck",
    		"-tagging.mangroup",
    		"politi.wardrobe",
    	},
	["Politi-Job"] = {
		_config = { gtype = "job"},
		"police.menu",
		--"politi.ledelse.doors",
		"politi.bank",
		"police.putinveh",
		"politi.onduty",
		"police.carsearch",
		"player.deletevehicle",
		"police.bodyarmor",
		"bank.police",
		"police.announce",
		"police.check",
		"police.easy_cuff",
		"police.easy_jail",
		"police.easy_unjail",
		"police.getoutveh",
		"police.jail",
		"-police.seizable", -- negative permission, police can't seize itself, even if another group add the permission
		"police.seize.items",
		"police.seize.weapons",
		"police.fine",
		"police.service",
		"police.store_weapons",
		"police.store_money",
		"police.wanted",
		"emergency.revive",
		"holdup.police",
		"police.besked",
		"police.drag",
		"police.easy_fine",
		"police.garage",
		"policeheli.garage",
		"police.loadshop",
		"police.menu_interaction",
		"police.spikes",
		"police.handcuff",
		"police.license",
		-- Paychecks
		"politiledelse.paycheck",
		"politiviceledelse.paycheck",
		"policedirector.paycheck",
		"policevicedirector.paycheck",
		"policeinspector.paycheck",
		"policecommissioner.paycheck",
		"politiassistent.paycheck",
		"police.paycheck",
		"politielev.paycheck",
	},
	["Regionschef"] = {
		_config = { gtype = "EMS-Job",order=5},
		"-doctor.paycheck",
		"-paramediciner.paycheck",
		"-emergency.paycheck",
		"-emergencyelev.paycheck",
		"emergency.key",
		"ems.duty",
		"ems.mangroup",
		"ems.wardrobe",
	},
	["Læge"] = {
		_config = { gtype = "EMS-Job",order=4},
		"-regionschef.paycheck",
		"-paramediciner.paycheck",
		"-emergency.paycheck",
		"-emergencyelev.paycheck",
		"emergency.key",
		"ems.duty",
		"ems.wardrobe",
	},
	["Paramediciner"] = {
		_config = { gtype = "EMS-Job",order=3},
		"-regionschef.paycheck",
		"-doctor.paycheck",
		"-emergency.paycheck",
		"-emergencyelev.paycheck",
		"emergency.key",
		"ems.duty",
		"ems.wardrobe",
	},
	["Ambulanceredder"] = {
		_config = { gtype = "EMS-Job",order=2},
		"-regionschef.paycheck",
		"-doctor.paycheck",
		"-paramediciner.paycheck",
		"-emergencyelev.paycheck",
		"emergency.key",
		"ems.duty",
		"ems.wardrobe",
	},
	["Ambulanceelev"] = {
		_config = { gtype = "EMS-Job",order=1},
		"-regionschef.paycheck",
		"-doctor.paycheck",
		"-paramediciner.paycheck",
		"-emergency.paycheck",
		"emergency.key",
		"ems.duty",
		"ems.wardrobe",
	},
	["EMS-Job"] = {
		_config = { gtype = "job" },
		"emergency.revive",
		"player.deletevehicle",
		"emergency.shop",
		"emergency.service",
		"emergency.market",
		"emergency.putinveh",
		"emergency.besked",
		"emergency.getoutveh",
		"emergency.drag",
		"emergency.heal",
		"emergency.garage",
		"emergency.cloakroom",
		"regionschef.paycheck",
		"doctor.paycheck",
		"paramediciner.paycheck",
		"emergency.paycheck",
		"emergencyelev.paycheck",
		"emergency.menu",
		"delivery.medic",
		"police.menu_interaction",
		"mission.emergency.transfer"
	},
	["Mekaniker Chef"] = {
		_config = { gtype = "Mekaniker-Job",order=3},
		"-mekaniker.paycheck",
		"mekaniker.duty",
		"mekaniker.kursus",
		"mekaniker.mangroup",
		"mekaniker.wardrobe",
		"repair.loadshop",
		"domingo.loadshop",
		"domingo.adgang",
		"domingomekaniker.duty",
		"mekaniker.adgang",

	},
	["Mekaniker Domingo"] = {
		_config = { gtype = "Mekaniker-Job",order=2},
		"-mekanikerchef.paycheck",
		"domingomekaniker.duty",
		"mekaniker.wardrobe",
		"repair.loadshop",
		"domingo.loadshop",
		"mekaniker.adgang",
		"domingo.adgang",

	},
	["Mekaniker Civilians"] = {
		_config = { gtype = "Mekaniker-Job",order=1},
		"-mekanikerchef.paycheck",
		"civiliansmekaniker.duty",
		"mekaniker.wardrobe",
		"repair.loadshop",
		"civilians.loadshop",
		"mekaniker.adgang",
		"civilians.adgang",

	},
	["Mekaniker-Job"] = {
		_config = { gtype = "job"},
		"vehicle.repair",
		"repair.loadshop",
		"player.deletevehicle",
		"vehicle.replace",
		"repair.service",
		"repair.paycheck",
		"mekaniker.paycheck",
		"mekanikerchef.paycheck",
		"repair.besked",
		"repair.menu",
		"police.menu_interaction"
	},
	["Taxi"] = {
		_config = { gtype = "job" },
		"taxi.service",
		"taxi.garage",
		"taxi.paycheck",
		"taxi.besked",
		"mission.taxi.passenger"
	},
	["Indbrudstyv"] = {
		_config = { gtype = "job" },
		"indbrudstyv.adgang",
		"nojob.paycheck"
	},
	["Våbendealer"] = {
		_config = { gtype = "Våbendealer-Job" },
		"blacklisted.weapons",
		"weapons.dealer",
		"weapondealer.wardrobe"
	},
	["Våbendealer-Job"] = {
		_config = { gtype = "job" },
		"player.store_money",
		"player.replaceplate",
		"drugdealer.garage",
		"weapondealer.paycheck",
	},
	["Drugdealer"] = {
		_config = { gtype = "Drugdealer-Job" },
		"blacklisted.weapons",
		"drug.dealer",
		"drugdealer.adgang",
		"producent.adgang",
		
	},
	["Drugdealer-Job"] = {
		_config = { gtype = "job" },
		"player.store_money",
		"player.replaceplate",
		"drugdealer.paycheck",
		"drugdealer.garage",
		"drugdealer.adgang",
		"drugdealer.menu",
		"drugdealer.wardrobe"
	},
	["Kemiker"] = {
		_config = { gtype = "job"},
		"kemiker.adgang",
		"nojob.paycheck"
	},
	["Pusher"] = {
		_config = { gtype = "job"},
		"pusher.adgang",
		"nojob.paycheck"
	},
	["Producent"] = {
		_config = { gtype = "job"},
		"producent.adgang",
		"nojob.paycheck"
	},
	["Advokat Chef"] = {
		_config = {  gtype = "Advokat-Job",order=4 },
		"-advokat.paycheck",
		"-advokatelev.paycheck",
		"-advokatpartner.paycheck",
		"advokatchef.paycheck",
		"advokat.duty",
		"advokat.garage",
		"advokat.mangroup"

	},
	["Advokat Partner"] = {
		_config = {  gtype = "Advokat-Job",order=3 },
		"-advokat.paycheck",
		"-advokatchef.paycheck",
		"-advokatelev.paycheck",
		"advokatpartner.paycheck",
		"advokat.duty",
		"advokat.garage",
		"advokat.mangroup"

	},
	["Advokat"] = {
		_config = {  gtype = "Advokat-Job",order=2 },
		"-advokatchef.paycheck",
		"-advokatelev.paycheck",
		"-advokatpartner.paycheck",
		"advokat.paycheck",
		"advokat.duty",
		"advokat.garage",
		"advokat.mangroup"

	},
	["Advokatelev"] = {
		_config = {  gtype = "Advokat-Job",order=1 },
		"-advokatchef.paycheck",
		"-advokat.paycheck",
		"-advokatpartner.paycheck",
		"advokatelev.paycheck",
		"advokat.garage",
		"advokat.duty",
		"advokat.wardrobe"
	},
	["Advokat-Job"] = {
		_config = {  gtype = "job" },
		"advokat.service",
		"advokat.paycheck",
		"advokatchef.paycheck"
	},

	["Politiadvokat Chef"] = {
		_config = {  gtype = "Politiadvokat-Job",order=2 },
		"-politiadvokat.paycheck",
		"politiadvokat.duty",
		"politiadvokat.mangroup",
		"police.cloakroom",
		"tagging.mangroup",
		"politi.wardrobe",
	},
	["Politiadvokat"] = {
		_config = {  gtype = "Politiadvokat-Job",order=1 },
		"-politiadvokatchef.paycheck",
		"politiadvokat.duty",
	},
	["Politiadvokat-Job"] = {
		_config = {  gtype = "job" },
		"advokat.service",
		"politiadvokat.paycheck",
		"politiadvokatchef.paycheck",
		"police.pc"
	},
	["Sikkerhedsvagt Chef"] = {
		_config = {  gtype = "Sikkerhedsvagt-Job",order=3 },
		"-sikkerhedsvagt.paycheck",
		"security.key",
		"sikkerhedsvagt.duty",
		"sikkerhedsvagt.mangroup"
	},
	["Sikkerhedsvagt"] = {
		_config = {  gtype = "Sikkerhedsvagt-Job",order=2 },
		"-sikkerhedsvagtchef.paycheck",
		"security.key",
		"sikkerhedsvagt.duty",
	},
	["Sikkerhedsvagt Assistent"] = {
		_config = {  gtype = "Sikkerhedsvagt-Job",order=1 },
		"-sikkerhedsvagtchef.paycheck",
		"security.key",
		"sikkerhedsvagt.duty",

	},
	["Sikkerhedsvagt-Job"] = {
		_config = {  gtype = "job" },
		"sikkerhedsvagt.service",
		"sikkerhedsvagt.paycheck",
		"sikkerhedsvagtchef.paycheck",
		"police.easy_cuff",
		"police.handcuff",
		"security.key",
		"security.vehicle"
	},
	["Miner"] = {
		_config = {  gtype = "job" },
		"miner.adgang",
		"miner.paycheck"
	},

	["Skovhugger"] = {
		_config = {  gtype = "job" },
		"skovhugger.tree",
		"skovhugger.paycheck",
		"skov.vehicle",
		"skovhugger.adgang"
	},
	["Skraldemand"] = {
		_config = { gtype = "job" },
		"skralde.vehicle",
		"mission.skraldemand"
	},
	["Pizzabud"] = {
		_config = {
			gtype = "job",
			onjoin = function(player)
				TriggerClientEvent("pNotify:SendNotification", player,{text = "Du er nu Pizzabud.", type = "success", queue = "global", timeout = 5000, layout = "centerLeft",animation = {open = "gta_effects_fade_in", close = "gta_effects_fade_out"}})
			end,
			onspawn = function(player) end,
			onleave = function(player) vRPclient.stopMission(player) end
		},
		"delivery.vehicle",
		"delivery.paycheck",
		"delivery.pizza"
	},
	["Farmer"] = {
		_config = { gtype = "job" },
		"mission.farmer1",
		"mission.farmer2",
		"farmer.adgang"
	},
	["Lastbilchauffør"] = {
		_config = { gtype = "job" },
		"delivery.trucker",
		"trucker.vehicle",
		"trucker.paycheck"
	},
	["Kørelærer-Job"] = {
		_config = { gtype = "job" },
		"driverlicense.paycheck"
	},
	["Tagging"] = {
		_config = { gtype = "tagging"},

	},

	["Arbejdsløs"] = {
		_config = { gtype = "job" },
		"nojob.paycheck",
	},
	
	["Druglord"] = {
		"druglord.adgang",
	},	
}

-- groups are added dynamically using the API or the menu, but you can add group when an user join here
cfg.users = {
	[76] = { -- give superadmin and admin group to the first created user on the database
		"ledelse",
		"staff"
	},
	[107] = { -- give superadmin and admin group to the first created user on the database
		"ledelse",
		"staff"
	}
}

-- group selectors
-- _config
--- x,y,z, blipid, blipcolor, permissions (optional)

cfg.selectors = {
}

return cfg
