local cfg = {}

cfg.showgarage = {
	vehicles = {
		--Eksklusiv
		{name = "Elegy Retro", costs = 1500000, description = {}, model = "elegy"},


		--Kompakte
		{name = "Emperor", costs = 40000, description = {}, model = "emperor"},
		{name = "Blista", costs = 50000, description = {}, model = "blista"},
		{name = "Blista Compact", costs = 60000, description = {}, model = "blista2"},
		{name = "Brioso R/A", costs = 75000, description = {}, model = "brioso"},
		{name = "Dilettante", costs = 50000, description = {}, model = "Dilettante"},
		{name = "Issi", costs = 60000, description = {}, model = "issi2"},
		{name = "Issi Classic", costs = 40000, description = {}, model = "issi3"},
		{name = "Panto", costs = 60000, description = {}, model = "panto"},
		{name = "Prairie", costs = 75000, description = {}, model = "prairie"},
		{name = "Rhapsody", costs = 50000, description = {}, model = "rhapsody"},


		--Coupéer
		{name = "Specter", costs = 2700000, description = {}, model = "specter"},
		{name = "Specter CTM", costs = 2800000, description = {}, model = "specter2"},
		{name = "Cognoscenti Cabrio", costs = 2400000, description = {}, model = "cogcabrio"},
		{name = "F620", costs = 2300000, description = {}, model = "f620"},
		{name = "Felon GT", costs = 1900000, description = {}, model = "felon2"},
		{name = "Jackal", costs = 1600000, description = {}, model = "jackal"},
		{name = "Oracle", costs = 1400000, description = {}, model = "oracle"},
		{name = "Oracle XS", costs = 1750000, description = {}, model = "oracle2"},
		{name = "Sentinel", costs = 900000, description = {}, model = "sentinel"},
		{name = "Sentinel XS", costs = 1000000, description = {}, model = "sentinel2"},
		{name = "Windsor", costs = 2400000, description = {}, model = "windsor"},
		{name = "Windsor Drop", costs = 2600000, description = {}, model = "windsor2"},
		{name = "Zion", costs = 1700000, description = {}, model = "zion"},
		{name = "Zion Cabrio", costs = 1800000, description = {}, model = "zion2"},


		--Sports biler (GTA)
		{name = "Neon", costs = 0, description = {}, model = "neon"},
		{name = "Comet", costs = 0, description = {}, model = "comet"},
		{name = "Comet SR", costs = 0, description = {}, model = "comet5"},
		{name = "Comet Custom", costs = 0, description = {}, model = "comet3"},
		{name = "Banshee", costs = 0, description = {}, model = "banshee"},
		{name = "Bestia GTS", costs = 0, description = {}, model = "bestiagts"},
		{name = "Buffalo", costs = 0, description = {}, model = "buffalo"},
		{name = "Buffalo S", costs = 0, description = {}, model = "buffalo2"},
		{name = "Carbonizzare", costs = 0, description = {}, model = "carbonizzare"},
		{name = "Coquette", costs = 0, description = {}, model = "coquette"},
		{name = "Feltzer", costs = 0, description = {}, model = "feltzer2"},
		{name = "Furore GT", costs = 0, description = {}, model = "furoregt"},
		{name = "Fusilade", costs = 0, description = {}, model = "fusilade"},
		{name = "Jester", costs = 0, description = {}, model = "jester"},
		{name = "Jester(Racerbil)", costs = 0, description = {}, model = "jester2"},
		{name = "Kuruma", costs = 0, description = {}, model = "kuruma"},
		{name = "Lynx", costs = 0, description = {}, model = "lynx"},
		{name = "Massacro", costs = 0, description = {}, model = "massacro"},
		{name = "Massacro(Racecar)", costs = 0, description = {}, model = "massacro2"},
		{name = "Omnis", costs = 0, description = {}, model = "omnis"},
		--{name = "Penumbra", costs = 0, description = {}, model = "penumbra"},
		{name = "Rapid GT", costs = 0, description = {}, model = "rapidgt"},
		{name = "Rapid GT Convertible", costs = 0, description = {}, model = "rapidgt2"},
		{name = "Schafter V12", costs = 0, description = {}, model = "schafter3"},
		{name = "Surano", costs = 0, description = {}, model = "surano"},
		{name = "Tropos", costs = 0, description = {}, model = "tropos"},
		{name = "Verkierer", costs = 0, description = {}, model = "verlierer2"},
		{name = "Schlagen GT", costs = 0, description = {}, model = "Schlagen"},
		{name = "Pariah", costs = 0, description = {}, model = "pariah"},
		{name = "Khamelion", costs = 0, description = {}, model = "khamelion"},
		{name = "Raptor", costs = 0, description = {}, model = "raptor"},
		{name = "Ruston", costs = 0, description = {}, model = "ruston"},
		{name = "Dominator GTX", costs = 0, description = {}, model = "dominator3"},
		{name = "Sultan", costs = 0, description = {}, model = "sultan"},
		{name = "Elegy RH 8", costs = 0, description = {}, model = "elegy2"},
		{name = "Revolter", costs = 0, description = {}, model = "revolter"},
		{name = "Dewbacca 70", costs = 0, description = {}, model = "seven70"},
	--	{name = "Banshee 900R", costs = 0, description = {}, model = "banshee2"},
		{name = "Voltic", costs = 0, description = {}, model = "voltic"},
		{name = "Sheava", costs = 0, description = {}, model = "sheava"},
	--	{name = "Sentinel Classic", costs = 0, description = {}, model = "sentinel3"},
		{name = "Jester MK4", costs = 0, description = {}, model = "jester3"},
	--	{name = "Flash GT", costs = 0, description = {}, model = "flashgt"},
		{name = "FMJ", costs = 0, description = {}, model = "fmj"},
		{name = "Osiris", costs = 0, description = {}, model = "osiris"},
		{name = "Penetrator", costs = 0, description = {}, model = "penetrator"},
		{name = "GB200", costs = 0, description = {}, model = "gb200"},
		{name = "Michelli", costs = 0, description = {}, model = "michelli"},



		--Sports klassikere
		{name = "Rapid GT", costs = 0, description = {}, model = "rapidgt3"},
		{name = "Retinue", costs = 0, description = {}, model = "retinue"},
		{name = "Torero", costs = 0, description = {}, model = "torero"},
	--	{name = "Cheetah Classic", costs = 0, description = {}, model = "cheetah2"},
		{name = "GT500", costs = 0, description = {}, model = "gt500"},
		{name = "Hermes", costs = 0, description = {}, model = "hermes"},
		{name = "Casco", costs = 0, description = {}, model = "casco"},
		{name = "Coquette Classic", costs = 0, description = {}, model = "coquette2"},
		{name = "Pigalle", costs = 0, description = {}, model = "pigalle"},
		{name = "Stinger", costs = 0, description = {}, model = "stinger"},
		{name = "Stinger GT", costs = 0, description = {}, model = "stingergt"},
		{name = "Stirling GT", costs = 0, description = {}, model = "feltzer3"},
		{name = "Z-Type", costs = 0, description = {}, model = "ztype"},
		{name = "Stafford", costs = 0, description = {}, model = "stafford"},
		{name = "Infernus Classic", costs = 0, description = {}, model = "infernus2"},
		{name = "Monroe", costs = 0, description = {}, model = "monroe"},
		{name = "Turismo Classic", costs = 0, description = {}, model = "turismo2"},
		{name = "Viseris", costs = 0, description = {}, model = "viseris"},
		{name = "Z190", costs = 0, description = {}, model = "z190"},
		{name = "Clique Veteran", costs = 0, description = {}, model = "clique"},
		{name = "Mamba", costs = 0, description = {}, model = "mamba"},


		--Supers
		{name = "Adder", costs = 0, description = {}, model = "adder"},
		{name = "Nero", costs = 0, description = {}, model = "nero"},
		{name = "Taipan", costs = 0, description = {}, model = "taipan"},
		{name = "Entity XF", costs = 0, description = {}, model = "entityxf"},
		{name = "Entity XXR", costs = 0, description = {}, model = "entity2"},
		{name = "811", costs = 0, description = {}, model = "pfister811"},
		{name = "Cyclone", costs = 0, description = {}, model = "cyclone"},
		{name = "Reaper", costs = 0, description = {}, model = "reaper"},
		{name = "Tyrant", costs = 0, description = {}, model = "tyrant"},
		{name = "Itali GTB", costs = 0, description = {}, model = "italigtb"},
		{name = "Itali GTO", costs = 0, description = {}, model = "italigto"},
		{name = "T20", costs = 0, description = {}, model = "t20"},
		{name = "Tursimo R", costs = 0, description = {}, model = "turismor"},
		{name = "Zentorno", costs = 0, description = {}, model = "zentorno"},
		{name = "Vacca", costs = 0, description = {}, model = "vacca"},
		{name = "Bullet", costs = 0, description = {}, model = "bullet"},
		{name = "Cheetah", costs = 0, description = {}, model = "cheetah"},
		{name = "Infernus", costs = 0, description = {}, model = "infernus"},
		{name = "Itali GTB 2", costs = 0, description = {}, model = "italigtb2"},
		{name = "GP1", costs = 0, description = {}, model = "gp1"},
		{name = "Tyrus", costs = 0, description = {}, model = "tyrus"},
	--	{name = "Tempesta", costs = 0, description = {}, model = "tempesta"},
		{name = "X80 Proto", costs = 0, description = {}, model = "prototipo"},
		{name = "Autarch", costs = 0, description = {}, model = "autarch"},
		{name = "Vagner", costs = 0, description = {}, model = "vagner"},



		--Muskel biler
		{name = "Blade", costs = 325000, description = {}, model = "blade"},
		{name = "Buccaneer", costs = 250000, description = {}, model = "buccaneer"},
		{name = "Chino", costs = 225000, description = {}, model = "chino"},
		{name = "Coquette BlackFin", costs = 695000, description = {}, model = "coquette3"},
		{name = "Dominator", costs = 625000, description = {}, model = "dominator"},
		{name = "Dukes", costs = 575000, description = {}, model = "dukes"},
		{name = "Hotknife", costs = 610000, description = {}, model = "hotknife"},
		{name = "Faction", costs = 545000, description = {}, model = "faction"},
		{name = "Nightshade", costs = 475000, description = {}, model = "nightshade"},
		{name = "Picador", costs = 715000, description = {}, model = "picador"},
		{name = "Sabre Turbo", costs = 489000, description = {}, model = "sabregt"},
		{name = "Tampa", costs = 660000, description = {}, model = "tampa2"},
		{name = "Virgo", costs = 150000, description = {}, model = "virgo"},
		{name = "Hustler", costs = 695000, description = {}, model = "hustler"},
		{name = "Btype 2", costs = 1500000, description = {}, model = "btype2"},
		{name = "Tornado V8", costs = 700000, description = {}, model = "tornado6"},
		{name = "Impaler", costs = 1250000, description = {}, model = "impaler"},
		{name = "Ruiner 2", costs = 1350000, description = {}, model = "ruiner2"},
		{name = "Imperator", costs = 900000, description = {}, model = "imperator"},
		{name = "Vamos", costs = 895000, description = {}, model = "vamos"},
	    {name = "Faction Custom", costs = 1750000, description = {}, model = "faction3"},
	    {name = "Slamvan Custom", costs = 2500000, description = {}, model = "slamvan3"},
	    {name = "Tornado Custom", costs = 1450000, description = {}, model = "tornado5"},
	    {name = "Virgo Custom", costs = 1350000, description = {}, model = "virgo2"},
	    {name = "Sabre GT Custom", costs = 2350000, description = {}, model = "sabregt2"},		


		--Offroad
		{name = "Kamacho", costs = 315000, description = {}, model = "kamacho"},
		{name = "Riata", costs = 325000, description = {}, model = "riata"},
		{name = "Streiter", costs = 225000, description = {}, model = "streiter"},
		{name = "Bifta", costs = 75000, description = {}, model = "bifta"},
		{name = "Blazer", costs = 10000, description = {}, model = "blazer"},
		{name = "Brawler", costs = 725000, description = {}, model = "brawler"},
		{name = "Dubsta 6x6", costs = 375000, description = {}, model = "dubsta3"},
		{name = "Dune Buggy", costs = 200000, description = {}, model = "dune"},
		{name = "Rebel", costs = 220000, description = {}, model = "rebel2"},
		{name = "Sandking", costs = 175000, description = {}, model = "sandking"},
		{name = "Trophy Truck", costs = 575000, description = {}, model = "trophytruck"},
		{name = "Contender", costs = 375000, description = {}, model = "contender"},
		{name = "Mesa Camo", costs = 475000, description = {}, model = "mesa3"},
	--	{name = "Trophy Truck 2", costs = 650000, description = {}, model = "trophytruck2"},
		{name = "Guardian", costs = 495000, description = {}, model = "guardian"},
		{name = "Comet Rally", costs = 2000000, description = {}, model = "comet4"},


		--Suver
		{name = "Baller", costs = 0, description = {}, model = "baller"},
		{name = "Baller 2", costs = 0, description = {}, model = "baller2"},
		{name = "Baller LE", costs = 0, description = {}, model = "baller3"},
		{name = "Baller LE LWD", costs = 0, description = {}, model = "baller4"},
		{name = "Dubsta", costs = 0, description = {}, model = "dubsta"},
		{name = "Dubsta 2", costs = 0, description = {}, model = "dubsta2"},
		{name = "Toros", costs = 0, description = {}, model = "toros"},
		{name = "Patriot Stretch", costs = 0, description = {}, model = "patriot2"},
		{name = "Contender", costs = 0, description = {}, model = "contender"},
		{name = "XLS", costs = 0, description = {}, model = "xls"},
		--{name = "Rocoto", costs = 0, description = {}, model = "rocoto"},
		{name = "Gresley SRT", costs = 0, description = {}, model = "gresleysrt"},
		{name = "Cavalcade", costs = 0, description = {}, model = "cavalcade"},
		{name = "Huntley", costs = 0, description = {}, model = "huntley"},
		{name = "FQ2", costs = 0, description = {}, model = "fq2"},
		{name = "Patriot", costs = 0, description = {}, model = "patriot"},


		--Varevogne
		{name = "Moonbeam", costs = 450000, description = {}, model = "moonbeam2"},
		{name = "Yosemite", costs = 285000, description = {}, model = "yosemite"},
		{name = "Bison", costs = 130000, description = {}, model = "bison"},
		{name = "Bobcat XL", costs = 123000, description = {}, model = "bobcatxl"},
		{name = "Gang Burrito", costs = 245000, description = {}, model = "gburrito"},
		{name = "Journey", costs = 150000, description = {}, model = "journey"},
		{name = "Minivan", costs = 300000, description = {}, model = "minivan"},
		{name = "Paradise", costs = 250000, description = {}, model = "paradise"},
		{name = "Rumpo", costs = 130000, description = {}, model = "rumpo"},
		{name = "Surfer", costs = 110000, description = {}, model = "surfer"},
		{name = "Youga", costs = 160000, description = {}, model = "youga"},
		{name = "Youga 2", costs = 155000, description = {}, model = "youga2"},
		{name = "Granger", costs = 315000, description = {}, model = "granger"},
		{name = "Brute Pony", costs = 195000, description = {}, model = "pony"},
		{name = "Brute Smoke", costs = 225000, description = {}, model = "ponys"},


		--Custom / Import biler
		{name = "Chrysler Crossfire", costs = 0, description = {"Køb ved fysisk bilforhandler"}, model = "srt6r "},
		{name = "BMW M3 E36", costs = 0, description = {"Køb ved fysisk bilforhandler"}, model = "rmodm3e36"},
		{name = "Volvo S60 POLE", costs = 0, description = {"Køb ved fysisk bilforhandler"}, model = "s60pole"},
		{name = "BMW 530D", costs = 0, description = {"Køb ved fysisk bilforhandler"}, model = "540l"},
		{name = "Aston Martin Vantage", costs = 0, description = {"Køb ved fysisk bilforhandler"}, model = "vantage"},
		{name = "Mercedes Benz C250", costs = 0, description = {"Køb ved fysisk bilforhandler"}, model = "mc250"},
		{name = "Ford Mustang Boss 302", costs = 0, description = {"Køb ved fysisk bilforhandler"}, model = "boss302"},
		{name = "Suzuki RMZ 250cc", costs = 0, description = {"Køb ved fysisk bilforhandler"}, model = "rmzsm"},

		--Sedan
		{name = "Raiden", costs = 2500000, description = {}, model = "raiden"},
		{name = "Asea", costs = 225000, description = {}, model = "asea"},
		{name = "Asterope", costs = 275000, description = {}, model = "asterope"},
		{name = "Cognoscenti", costs = 2200000, description = {}, model = "cognoscenti"},
		{name = "Cognoscenti 55", costs = 2000000, description = {}, model = "cog55"},
		{name = "Glendale", costs = 195000, description = {}, model = "glendale"},
		{name = "Ingot", costs = 85000, description = {}, model = "ingot"},
		{name = "Intruder", costs = 250000, description = {}, model = "intruder"},
		{name = "Premier", costs = 210000, description = {}, model = "premier"},
		{name = "Primo", costs = 235000, description = {}, model = "primo"},
		{name = "Primo Custom", costs = 275000, description = {}, model = "primo2"},
		{name = "Regina", costs = 175000, description = {}, model = "regina"},
		{name = "Schafter", costs = 625000, description = {}, model = "schafter2"},
		--{name = "Stanier", costs = 100000, description = {}, model = "stanier"},
		{name = "Stratum", costs = 100000, description = {}, model = "stratum"},
		{name = "Super Diamond", costs = 1700000, description = {}, model = "superd"},
		{name = "Surge", costs = 240000, description = {}, model = "surge"},
		{name = "Tailgater", costs = 600000, description = {}, model = "tailgate"},
		{name = "Warrener", costs = 175000, description = {}, model = "warrener"},
		{name = "Washington", costs = 225000, description = {}, model = "washingt"},
		{name = "Minivan Custom", costs = 850000, description = {}, model = "minivan2"},


		--Motorcykler
		{name = "Akuma", costs = 90000, description = {}, model = "AKUMA"},
		{name = "Bagger", costs = 50000, description = {}, model = "bagger"},
		{name = "Bati 801", costs = 150000, description = {}, model = "bati"},
		{name = "Bati 801RR", costs = 160000, description = {}, model = "bati2"},
		{name = "BF400", costs = 300000, description = {}, model = "bf400"},
		{name = "Carbon RS", costs = 180000, description = {}, model = "carbonrs"},
		{name = "Cliffhanger", costs = 325000, description = {}, model = "cliffhanger"},
		{name = "Double T", costs = 112000, description = {}, model = "double"},
		{name = "Faggio", costs = 13000, description = {}, model = "faggio2"},
		{name = "Gargoyle", costs = 220000, description = {}, model = "gargoyle"},
		{name = "Innovation", costs = 190000, description = {}, model = "innovation"},
		{name = "PCJ-600", costs = 90000, description = {}, model = "pcj"},
		{name = "Zombie Chobber", costs = 385000, description = {}, model = "zombieb"},
		{name = "Vindicator", costs = 600000, description = {}, model = "vindicator"},
		{name = "Sanchez", costs = 80000, description = {}, model = "sanchez"},
		{name = "Nightblade", costs = 400000, description = {}, model = "nightblade"},
		{name = "Sanctus", costs = 2200000, description = {}, model = "sanctus"},
		{name = "Hexer", costs = 120000, description = {}, model = "hexer"},
		{name = "Daemon", costs = 200000, description = {}, model = "daemon"},
		{name = "Nemesis", costs = 120000, description = {}, model = "nemesis"},
		{name = "Ruffian", costs = 210000, description = {}, model = "ruffian"},
		{name = "Vader", costs = 200000, description = {}, model = "vader"},
		{name = "Thrust", costs = 323000, description = {}, model = "thrust"},
		{name = "Hakuchou", costs = 650000, description = {}, model = "hakuchou"},
		{name = "Blazer4", costs = 430000, description = {}, model = "blazer4"},
		{name = "Fcr 2", costs = 1350000, description = {}, model = "fcr2"},
		{name = "Manchez", costs = 600000, description = {}, model = "manchez"},
		{name = "Defiler", costs = 995000, description = {}, model = "defiler"},
	}
}

return cfg
