var tableauQuestion = [
    {   question : "Hvor hurtigt må du køre på motorvejen, hvis der ikke er nogen skiltning?",
        propositionA : "100 km/t",
        propositionB : "110 km/t",
        propositionC : "120 km/t",
        propositionD : "130 km/t",
        reponse : "D"},

    {   question : "Hvad er fartgrænsen på landevejen?",
        propositionA : "90 km/t",
        propositionB : "80 km/t",
        propositionC : "100 km/t",
        propositionD : "60 km/t",
        reponse : "B"},

    {   question : "Hvornår kan du blive dømt for spritkørsel?",
        propositionA : "Når promillegræsen er 0.5, men jeg kan også blive dømt for spritkørsel, hvis jeg kører uansvarligt med en lavere promille.",
        propositionB : "Jeg kan først blive dømt hvis min promille er over 1",
        propositionC : "Promillegrænsen er 0.5 og jeg kan ikke blive dømt for spritkørsel, hvis jeg køre med uansvarligt med en lavere promille.",
        propositionD : "Så længe jeg kører ansvarligt, er det ligemeget med promillen.",
        reponse : "A"},

    {   question : "Før hver baneændring skal du",
        propositionA : "Ikke være opmærksom",
        propositionB : "Tjekke dine blinde vinkler",
        propositionC : "Køre over den tilladte fartgrænse",
        propositionD : "Overhale højre om",
        reponse : "B"},

    {   question : "Hvad er fartgrænsen på en motortrafikvej, hvor der ikke er skiltning?",
        propositionA : "80 km/t",
        propositionB : "90 km/t",
        propositionC : "100 km/t ",
        propositionD : "Så længe jeg kører efter forholdene, bestemmer jeg selv.",
        reponse : "A"},

    {   question : "Der står en fodgænger og venter på at komme over fodgængerfeltet du skal dreje til venstre. Hvad gør du?",
        propositionA : "Sætter farten lidt op, så jeg er hurtigt forbi, og fodgængeren kan komme over",
        propositionB : "Standser og lader fodgængeren komme over",
        propositionC : "Fordi der ikke er lysrehgulering, så er jeg ikk forpligtet til at stoppe",
        propositionD : "Jeg dytter, inden jeg kører fordi, så jeg er sikker på at fodgængeren har set mig og ikke går over",
        reponse : "B"},

    {   question : "Hvad er tilladt?",
        propositionA : "At øge hastigheden, hvis jeg bliver overhalet",
        propositionB : "Undlade at spænde børn under 15 år fast",
        propositionC : "Køre venstre om et helleanlæg",
        propositionD : "Ingen af delene",
        reponse : "D"},

    {   question : "Hvornår er det tilladt at bruge hornet?",
        propositionA : "Når du hilser på en ven",
        propositionB : "Hvis nogen ikke har opdaget, at der er blevet grønt",
        propositionC : "Kun hvis du skal afværge en ulykke. I alle andre tilfælde er det forbudt.",
        propositionD : "Der er ikke nogen særlige regler for brugen af horn.",
        reponse : "C"},

    {   question : "Du kører inde i midt byen, og forude kan du se, at en bybus blinker ud fra stoppestedet. Hvad gør du",
        propositionA : "Jeg fortsætter. Den skal holde tilbage for mig",
        propositionB : "Jeg holder tilbage, som jeg har pligt til",
        propositionC : "Jeg sætter farten op for at komme hurtigt forbi",
        propositionD : "Jeg slår havariblinket til, for at vise dem bag mig at bussen skal ud",
        reponse : "B"},

    {   question : "Hvor dybt skal dækmønsteret være i dit køretøjs dæk?",
        propositionA : "1,6 mm",
        propositionB : "1,5 mm",
        propositionC : "Det er ligegyldigt hvir dybe mit dækmønster er",
        propositionD : "1,1 mm",
        reponse : "A"},
]
